/**
  * Aula env variables
 */
define( 'WPO_SCIM_TOKEN', getenv( 'WORDPRESS_WPO_SCIM_TOKEN' ) );
define( 'WPO_ALLOW_DEVELOPER_HOOKS', getenv( 'WORDPRESS_WPO_ALLOW_DEVELOPER_HOOKS' ) );
define( 'O365_PROFILE_IMG_PATH', getenv( 'WORDPRESS_O365_PROFILE_IMG_PATH' ) );
define( 'COOKIE_DOMAIN', getenv( 'WORDPRESS_COOKIE_DOMAIN' ) );